### ISSUE TITLE
getX 상태관리

### ISSUE THREAD

**Issue by MentalJava** [MentalJava/flufire-sample#3]

**Comment by kdjun97** [comment]
setState는 해당 함수를 호출했을 때, 해당 block의 body가 rebuild됩니다.
반면, GetBuilder<Controller>나, Obx를 사용하면, 저희가 원하는 부분의 변화만 rebuild시킬 수 있어요. 그쪽 한번 파보시면 좋을 것 같습니다. @MentalJava
